### ISSUE TITLE
graphiQl

### ISSUE THREAD

**Issue by headwinds** [srghma/functional-nextjs-typescript-apollo-boilerplate#9]
I've just forked your repo and got the example to appear here:

http://localhost:3000 

awesome!

But when I visit http://localhost:3000/graphiql  - I get a 404 - any ideas?

It looks like it could be something with next - in the terminal there is a log about:
```Client pings, but there's no entry for page: /graphiql```

**Comment by BjornMelgaard** [comment]
@headwinds dunno, will look, thanks)
